const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"日程信息管理",
			            "menuJump":"列表",
			            "tableName":"richeng"
			        },
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"个人便签管理",
					    "menuJump":"列表",
					    "tableName":"gerenbianqian"
					},
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"通讯录管理",
					    "menuJump":"列表",
					    "tableName":"tongxunlu"
					},
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"请假记录管理",
					    "menuJump":"列表",
					    "tableName":"qingjiajilu"
					}
			    ],
			    "menu":"个人办公模块"
			}
            ,{
                "child":[
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"会议室管理",
					    "menuJump":"列表",
					    "tableName":"huiyishi"
					},
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"会议信息管理",
					    "menuJump":"列表",
					    "tableName":"huiyi"
					},
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"会议室预约管理",
                        "menuJump":"列表",
                        "tableName":"huiyishiyuyue"
                    }
                ],
                "menu":"会议管理模块"
            }
            ,{
                "child":[
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"员工管理",
					    "menuJump":"列表",
					    "tableName":"yonghu"
					},
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"系统管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "报表",
			                "删除"
			            ],
			            "menu":"考勤管理",
			            "menuJump":"列表",
			            "tableName":"kaoqin"
			        }
			    ],
			    "menu":"考勤管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "审核",
                            "删除"
                        ],
                        "menu":"文件信息管理",
                        "menuJump":"列表",
                        "tableName":"wenjian"
                    }
                ],
                "menu":"文件信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"部门信息管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBumen"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"岗位信息管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryGangwei"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"便签类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryGerenbianqian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"会议类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryHuiyi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"会议室类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryHuiyishi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"日程类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryRicheng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"联系人类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryTongxunlu"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"文件类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryWenjian"
			        }
			    ],
			    "menu":"基础数据管理"
			}
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"日程信息管理",
			            "menuJump":"列表",
			            "tableName":"richeng"
			        },
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"个人便签管理",
					    "menuJump":"列表",
					    "tableName":"gerenbianqian"
					},
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"通讯录管理",
					    "menuJump":"列表",
					    "tableName":"tongxunlu"
					},
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"请假记录管理",
					    "menuJump":"列表",
					    "tableName":"qingjiajilu"
					}
			    ],
			    "menu":"个人办公模块"
			}
	        ,{
	            "child":[
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"会议室管理",
					    "menuJump":"列表",
					    "tableName":"huiyishi"
					},
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"会议信息管理",
					    "menuJump":"列表",
					    "tableName":"huiyi"
					},
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"会议室预约管理",
	                    "menuJump":"列表",
	                    "tableName":"huiyishiyuyue"
	                }
	            ],
	            "menu":"会议管理模块"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"系统管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"考勤管理",
			            "menuJump":"列表",
			            "tableName":"kaoqin"
			        }
			    ],
			    "menu":"考勤管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"文件信息管理",
	                    "menuJump":"列表",
	                    "tableName":"wenjian"
	                }
	            ],
	            "menu":"文件信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"员工",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
